- setup.py
When using pip to uninstall the pyang package, the '.' caused all of
/usr/local/ to be removed.
> Remove the unused '.' path in data_files.

- pyang/plugin.py
Depending on the environment, it may be possible that sys.path expansion contains non-directories (e.g. zip) which could raise an OSError exception when attempting to os.listdir
> Implement try/except block for plugin directory listing

- .gitignore
- .travis.yml
- README.md
- Fix compatibility issues with python 3 - travis now run tests with python 2.7, 3.2, 3.3 and 3.4.
- Fixed warnings from pyflakes and py3kwarn static analysers. Added them to travis.
- Added coveralls test coverage report, with badge.
More details are in the messages from the individual commits.
Sorry for the pull-request confusion. I tried to create individual changes, but they turned out to be incompatible, conflicting with one another. This pull request has all changes, and passes all tests.
> Coveralls integration

- CHANGES
- bin/pyang
- doc/pyang.1.dbk
- etc/bash_completion.d/pyang
- man/man1/pyang.1
This adds a new --ignore-error option to ignore a named error.
The commit omits man page changes because the man pages appear to be generated using "make doc", but when I run "make doc" the resulting man page file doesn't appear to be valid.
> Fixes #203 - added command line flag --ignore-error

- pyang/plugins/sid.py
Structure IDentifier (SID) are used to map YANG definitions to
CBOR encoding. These SIDs can be automatically generated
for a YANG module using this sid plugin.
For more information, pyang --sid-help
References:
https://datatracker.ietf.org/doc/draft-turner-core-cool-problem-statement/
https://datatracker.ietf.org/doc/draft-somaraju-core-sid/ 
https://datatracker.ietf.org/doc/draft-veillette-core-yang-cbor-mapping/ 
https://datatracker.ietf.org/doc/draft-veillette-core-cool/
> New sid.py plugin

- pyang/plugin.py
- pyang/plugins/omni.py
- pyang/plugins/tree.py
- test/test_issues/Makefile
- test/test_issues/test_i230/Makefile
- test/test_issues/test_i230/example-sports.yang
As reported in #230 `string.split` was removed from python, and this makes pyang crash on python 3.
- Proposed solution:
* avoid using deprecated functions from `string` module, call functions directly on string object instead.
- Drawbacks:
* older versions of python may crash
- Advantages:
* works on python 3
> Fix #230 by calling split directly

- pyang/plugin.py
i.e. files whose names are of the form `.#xxx.py`.
Please let me know if you'd like an example that demonstrates the problem.
> Prevent importing temporary Emacs files

- .gitignore
- MANIFEST.in
- Makefile
1. Added `MANIFEST.in` file and included data files to it. In absence of `MANIFEST.in` data files are not included in source tarball. This makes pip to fail when installing from source tarball.
2. Removed `MANIFEST.in` creation from `Makefile`
> Include data files in source distribution tarball

- .gitignore
- .travis.yml
- pyang/__init__.py
- test/test_issues/Makefile
- test/test_issues/test_i225/Makefile
- test/test_issues/test_i225/test.sh
- test/test_issues/test_i225/test_prefix_deviation.py
For some systems `sys.prefix` is `/usr`, but python packages are installed in `/usr/local` by pip, as reported in #225.
With this change, pyang first tries the default location, and if it does not exist, asks  pip for the right one.
> Improve default implicit `$YANG_MODPATH` discovery

- pyang/plugins/tree.py
The output from pyang --tree-help looks strange for leafref types. Suggesting what I think it should be.
> Correct sentence in --tree-help output.

- bin/pyang
- etc/bash_completion.d/pyang
- pyang/__init__.py
- pyang/error.py
- pyang/grammar.py
- pyang/plugins/lint.py
- pyang/util.py
- Added --ensure-hyphentaed-names to catch identifiers/enum-args
which use camel-case or underscore
- Changed method _setup_ctx of class LintPlugin() to set
ensure_hyphenated_names to True. Since IETFPlugin() is a child
class of LintPlugin(), option --ietf will detect use of
camel-case or underscore
> Addressing https://github.com/mbj4668/pyang/issues/320

- bin/pyang
- pyang/__init__.py
- pyang/error.py
- pyang/syntax.py
- test/test_bad/1@2.yang
- test/test_bad/@2017-09-26.yang
- test/test_bad/badrev@2017-09.yang
- test/test_bad/expect/1@2.yang.out
- test/test_bad/expect/@2017-09-26.yang.out
- test/test_bad/expect/badrev@2017-09.yang.out
- test/test_bad/expect/norev@.yang.out
- test/test_bad/norev@.yang
Currently pyang is picky about the revision date in the filename (`r"\@(\d{4}-\d{2}-\d{2})"`) but not the module name (`r"^(.*?)"`) This means that file names with a misconstructed revision date get misinterpreted by pyang as having the revision date as part of the expected module name, e.g.:
```
pyang 'foo@2011-01-0.yang'
foo@2011-01-0.yang:1: warning: unexpected modulename "foo" in foo@2011-01-0.yang, should be foo@2011-01-0
```
This PR fixes the issue by making the module-name part of the filename match as equally picky as the revision part.
> Avoid misinterpreting malformed filenames

- pyang/__init__.py
Fix the following warning:
```
.../python3.5/site-packages/pyang/__init__.py:170: ResourceWarning: unclosed file <_io.TextIOWrapper name='xxx.yang' mode='r' encoding='utf-8'>
```
> Make sure to close open files

- pyang/error.py
- pyang/statements.py
- pyang/util.py
Use [`__slots__`](https://docs.python.org/3/reference/datamodel.html#slots) Python language feature to reduce the memory overhead of each `Statement` object. Also serves as a handy way to list all of the many possible Statement instance attributes in one place. In my testing this can reduce pyang's memory overhead by about **25%**.
Memory usage of my app using baseline `pyang` without this change:
```
(Pdb) from guppy import hpy
(Pdb) hpy().heap()
Partition of a set of 1569817 objects. Total size = 390492928 bytes.
Index  Count   %     Size   % Cumulative  % Kind (class / dict of class)
0  99535   6 156793960  40 156793960  40 dict of pyang.statements.Statement
1 665307  42 76017560  19 232811520  60 list
2  69021   4 37975224  10 270786744  69 dict (no owner)
3  99555   6 27875400   7 …
```
> Use __slots__ to reduce Statement memory usage

- pyang/types.py
This change allows plugins to use the typespec to get pattern restrictions. 
Without this change, plugins have to find the original `type` statement and then look for `pattern` substatements. Obviously that's error-prone if statements like `refine` are in play.
> Save the original pattern regexps in the typespec

- bin/json2xml
Fixes #402
If the key is missing in that case the execption raised
by lxml on calling remove() method is `TypeError`.
To fix this issue to display proper error message catch
`TypeError` exception.
> Fix json config validation error message

- doc/pyang.1.dbk
- etc/bash_completion.d/pyang
- pyang/plugins/tree.py
- test/test_tree/Makefile
- test/test_tree/ietf-interfaces-ext.tree.expect
- test/test_tree/ietf-interfaces.tree.expect
- test/test_tree/ietf-interfaces.yang
- test/test_tree/ietf-yang-types.yang
- test/test_tree/interfaces-ext.yang
This will assist with determining the naming required for inputs to json2xml.
Addresses #419
> Emit module name (instead of prefix) for augmented nodes when using tree format

- pyang/plugin.py
Emacs' flymake creates temporary files alongside the edited ones; flymake is started automatically when the buffer is saved, and if you start pyang at the same time, the temporary file would be used as another plugin (if the edited file happens to be a plugin).
> preventing flymake temp files to be used as plugins

- setup.py
The "%cd%" in the pyang.bat script returned the current working directory - hence the path "%cd%\pyang" pointed mostly to an non existing file. The new "%~dp0" returns the current directory location of the pyang.bat itself - that should the the same directory where the "pyang" file is installed.
> fixing pyang.bat on Windows

- pyang/statements.py
- pyang/yang_parser.py
Since most of the memory overhead of pyang is in Statement objects, and a surprising amount of the run time of pyang is spent in copying Statement objects (copying out from groupings, for example), anything we can do to reduce the size of a typical Statement and the number of distinct attributes it has can give us a lot of benefit performance-wise.
Some of the Statement attributes are generic and apply to a broad swath of YANG statements, but many are specific to one particular keyword or a small number of related keywords. Hence, by creating Statement subclasses for particular keywords and moving the attributes to those subclasses, we reduce the size of the average Statement by a significant amount. In my testing with a variety of YANG modules (including the quite large …
> Create Statement subclasses to waste less memory on unused __slots__.

- pyang/plugins/check_update.py
- test/test_update/Makefile
- test/test_update/expect/i.out
- test/test_update/i-sub.yang
- test/test_update/i.yang
- test/test_update/i@2014-04-01.yang
Issue 468 (https://github.com/mbj4668/pyang/issues/468) describes a problem where groupings moved to a submodule are not found by check-update resulting in incorrect error message that the grouping is not found. Note that the issue also applies to the typedef, extension, feature and identity statements.
The root cause is that chk_stmt does not find these statements when they have been moved to a submodule. The solution I'm proposing is to look in the respective dictionaries for groupings, typedefs, extensions, features and identities - this is what the new funcion chk_stmt_definitions provides.
New test cases are added to test the following:
Moving grouping, feature, typedef, extension, identity to a submodule - verify no error
Deleting grouping, feature, typedef, extension, identity - …
> Fix for Issue #468

- pyang/plugins/check_update.py
The changes above allow the plugin to be used as pyang API for checking compatibility on all platform modules with one time model context initialization.
> Resolved issues #483

- bin/json2xml
- test/test_json/amod.yang
If any of the yang modules used imports the ietf-netconf module yang2xml will register that namespace multiple times. This causes the generated XML to be invalid.
This PR ensures that the ietf-netconf namespace is only registered once.
> Ensure the ietf-netconf namespace isn't added multiple times

- pyang/xpath_parser.py
This PR adds some missing return statements in _mk_union, the lack of which resulted in a
TypeError exception being raised when parsing an XPath union with 3 or more terms. 
For example, attempting to validate this module:
```yang
module simple {
namespace "urn:example.com:simple";
prefix smpl;
description "Reproduce pyang 2.0.1 parse failure";
revision 2019-07-11 {
description "First version.";
}
container colours {
must "count(blue|yellow|green) = 1" {
error-message "Must specify just one of 'blue', 'yellow' or 'green'";
}
leaf green {
type uint16;
}
leaf blue {
type empty;
}
leaf yellow {
type uint16;
}
}
}
```
results in this traceback:
```
$ pyang simple.yang
Traceback (most recent call last):
File "/home/sbayley/.local/share/virtualenvs/pyang-lqqFW4m_/bin/pyang", line 7, in <module> …
```
> Fix TypeError when parsing XPath union

- pyang/plugins/uml.py
I believe the help for --uml-inline-augments should read "augmentations"
instead of "groupings", looks like a copy-paste error from the previous
option.
Signed-off-by: Quentin Young <qlyoung@cumulusnetworks.com>
> uml: s/groupings/augmentations in aug opt help

- pyang/error.py
- pyang/plugins/ietf.py
- pyang/plugins/smi.py
- pyang/plugins/tree.py
- pyang/statements.py
- pyang/syntax.py
Hi,
When running under Python3, we get a number of `DeprecationWarning: invalid escape sequence` warnings. This pull-request fixes these. I tried following the convention of using the raw-string `r""` prefix for regexp strings, or extra backslashes for other strings.
To avoid more of these creeping in, running `pycodestyle --select=W6 .` from the top of the code repository will flag this error.
> Fix invalid escape sequences

- pyang/plugins/bbf.py
- pyang/plugins/lint.py
I haven't added any tests. Do you need any?
(Note that this PR also modifies the lint plugin. I don't think this will affect any other plugins, because none of them set 'ensure_hyphenated_names'.)
> Align the --bbf option with the options that BBF uses for validating its modules

- .gitignore
- .travis.yml
- Makefile
- pyang/__init__.py
- test/Makefile
- test/test_issues/test_i505/Makefile
- test/test_verbose/Makefile
- test/test_verbose/expect/a.stderr
- test/test_verbose/expect/b.stderr
Long story: While preparing a patch for selftest, and general unification of file handling, I noticed make test took 3x more in my python3 virtualenv than normal. 
The reason was the import pip with an old pip (9.0.1 ships with bionic), vs. latest in my python2 virtualenv. E.g. setting YANG_INSTALL=$PWD skipped those imports, and the total runtime was comparable with current pips.
At least some improvements to the makefiles can be derived from that.
> Some further fixes to make test

- bin/pyang
- doc/pyang.1.dbk
- man/man1/pyang.1
- pyang/hello.py
EDIT: Added `--implicit-hello-deviations` flag to preserve original behavior. When flag is set, then will attempt to parse deviations from hello file which were not advertised as their own module.
Currently `deviations` specified in hello messages, e.g. `capabilities-ncs5500.xml`, etc. from YangModels/yang Cisco directories are not handled resulting in a schema which does not reflect the reality of those deviations. This adds logic to parse those deviations from the hello message.
e.g. https://github.com/YangModels/yang/blob/master/vendor/cisco/xr/701/cisco-xr-openconfig-routing-policy-deviations.yang#L33
Master:
```bash
(pyang) [701] grep neighbor-sets ncs5500-tree-orig.txt
|  +--rw neighbor-sets
|  |  |  +--rw neighbor-set?        -> …
```
> Add extended Hello parsing of deviations

- pyang/statements.py
- pyang/translators/yang.py
- pyang/yang_parser.py
- setup.cfg
- test/test_yang/expect/b.yang
- test/test_yang/expect/h.yang
- test/test_yang/h.yang
Hi Martin @mbj4668 ,  #547 is fixed. Please review this. 
1 It traverses the schema tree first to make a link list in order to look for the next statement to the current statement.
2 It adds two properties for the Comment Statement:`is_line_end`, `is_multi_line`. Compare current statement's position line number with the next comment's position line number for calculating the `is_line_end` property value.
3 End-of-line comments are separated by one space.
4 A test case is added in  `test_yang` module and `b.yang` has some small fixes for this feature.
> #547 feature:keep end-of-line comments

- pyang/translators/yang.py
Hi, Recently I researched the operations of dict. I determined to refactor the `has_key` function for a more reasonable style. I have tested the `configuration.yang` for both `python 2.7` and `python 3.7`, and It's OK.
> Refactor has_key operations on dict

- pyang/plugins/jtox.py
- test/test_issues/test_i501/Makefile
- test/test_issues/test_i501/mod1.yang
- test/test_issues/test_i501/mod11.yang
This PR fix #501   since` i_target_node` for leafref was processed differently between "yang-version 1.1" and "yang-version 1" with commit 8d7e549 , however, plugin `jtox` did not modify at the same time. So this commit fix this.
> Bugfix #501: fix plugin jtox crash for models with leafref in yang-version 1.1

- pyang/transforms/edit.py
As proposed by @mbj4668, arising from this comment:
> There is one option --edit-delete-xxx to delete xxx and the rest are --edit-yyy to set yyy.  Except --edit-previous-revision-date which deletes.  How about changing it to --edit-delete-previous-revision-date?
Upon further discussion we came up with --edit-delete-revision-after, which I've changed to --edit-delete-revisions-after in this PR (because more than one revision statement can be deleted).
> Change --edit-previous-revision-date to --edit-delete-revisions-after

- bin/yang2html
Since library `optparse` has been deprecated by Python 2.7, I replace `optparse` with `argparse`.
And add help message for argument `-c`
> Refactor yang2html: add -c help message AND replace optparse with argparse

- pyang/error.py
- pyang/statements.py
- test/test_bad/test_sec_7_15/expect/mod1.expect
- test/test_issues/test_i572/Makefile
- test/test_issues/test_i572/expect/mod1.expect
- test/test_issues/test_i572/expect/mod2.expect
- test/test_issues/test_i572/mod1.yang
- test/test_issues/test_i572/mod2.yang
Hi Martin, this PR Fix #572 
However, there are two more situations that I'm not sure in the RFC7950 for this:
1) When the action is in a grouping, then a list node without a key uses this grouping.
2)When an augment statement including an action, and the target node is a list node without a key.
> Bugfix #572: action or notification cannot have an ancestor list node without a "key"

- pyang/error.py
- pyang/statements.py
- test/test_bad/test_sec_7_20/expect/mod1.expect
- test/test_issues/test_i219/Makefile
- test/test_issues/test_i219/expect/mod1.expect
- test/test_issues/test_i219/expect/mod2.expect
- test/test_issues/test_i219/mod1.yang
- test/test_issues/test_i219/mod2.yang
- test/test_issues/test_i267/Makefile
Hi, This PR fix #219 
Meanwhile, another issue is found and fixed: 
When a comment substatement is in the deviate statement, it will report an error like
```
the "_comment" property does not exist in node "main::x"
```
However, I don't think this is an error.
> Bugfix deviation replace/add config should check the target node's config tree

- pyang/error.py
- pyang/grammar.py
- pyang/plugins/metadata.py
- pyang/plugins/restconf.py
- pyang/plugins/smi.py
- pyang/statements.py
- pyang/syntax.py
- pyang/types.py
- test/test_issues/test_i225/test.sh
Rebased previous PR; this time, setup should work without lxml already being installed.
The XSD pattern validation si something I've been originally told was missing in pyang, hence I independently came up with a solution that turned out to be already present. Given that LXML is now a requirement, it can always be used.
I do wonder about whether pyang should list as many errors as possible, (e.g. validate values against valid patterns, even if there was a pattern that was invalid in the type definition).
> Validation improvements

- pyang/statements.py
- test/test_issues/test_i606/Makefile
- test/test_issues/test_i606/expect/mod1.expect
- test/test_issues/test_i606/mod1.yang
> Bugfix #606: A definition of 'current' should not reference a 'deprecated' definition

- bin/pyang
Useful for informational purposes.
Previous behavior:
```
"xr/621/capabilities-ncs1k.xml": [
"module 'Cisco-IOS-XR-sysadmin-instmgr-cfg@2015-08-30' specified in hello not found."
],
```
Change behavior:
```
"xr/621/capabilities-ncs1k.xml": [
"module 'Cisco-IOS-XR-sysadmin-instmgr-cfg@2015-08-30' specified in hello not found.",
"module 'ietf-yang-smiv2@2011-11-25' specified in hello not found.",
"module 'ietf-yang-types@2010-09-24' specified in hello not found.",
"module 'Cisco-IOS-XR-sysadmin-services@2016-11-10' specified in hello not found.",
"module 'ietf-inet-types@2010-09-24' specified in hello not found.",
"module 'Cisco-IOS-XR-sysadmin-nto-misc-set-hostname@2016-10-13' specified in hello not found.",
"module 'ietf-yang-library@2016-06-21' specified in hello not found.",
"module …
```
> Output all missing Hello modules, then exit

- pyang/plugins/flatten.py
Previously module traversal was unsorted, yielding sorted modules themselves but unsorted in output order. This now sorts traversal of modules for XPaths as well.
> Sort top level modules in flatten traversal

- pyang/statements.py
- test/test_issues/test_i678/Makefile
- test/test_issues/test_i678/deviate-test.yang
- test/test_issues/test_i678/expect.yang
- test/test_issues/test_i678/target.yang
- test/test_issues/test_i678/types.yang
Fix the issue described in #678 
This is a regression introduced in release 2.2.0 with commit
**Code improvements for idiomatic python style** 
https://github.com/mbj4668/pyang/commit/b7c7683e0222ea597b58da9e118c8fe3ccc20070#diff-037294d92fe20ee53b92ebe8ae6ad7deR2184
The issue was the change from 
```
and c.arg.find(":") == -1
```
to 
```
and ':' in c.arg
```
The original logic checked that ```:``` was not found in the arg. Fix the issue by adding a ```not```
```
and ':' not in c.arg
```
This commit also adds a test case to reproduce the issue and verify the fix.
> Fix #678 deviate replace regression

- pyang/plugins/sample-xml-skeleton.py
- test/test_issues/test_i683/base.yang
- test/test_issues/test_i683/ext.yang
- test/test_issues/test_i683/main.expect
- test/test_issues/test_i683/main.yang
- test/test_issues/test_i683/makefile
The sample-xml-skeleton format can crash when generating XML for an imported module that isn't explicitly listed on the command line.
This PR fixes the problem by automatically adding namespaces for imported modules. It also avoids a crash should any namespaces still (for some reason) not be known.
I'll update the PR with a test.
> Fix sample-xml-skeleton unknown namespace crash

- pyang/statements.py
- test/test_issues/test_i690/Makefile
- test/test_issues/test_i690/main.expect
- test/test_issues/test_i690/test.yang
- test/test_issues/test_i690/test2.yang
1 Allow module circular import error to print explicitly.
2 If any module circular import error exists, stop the further uses expanding.
Hi @mbj4668 , this need you to review. I am not quite sure the solution is good. Or maybe something is left out by me.
> Fix#690 import circular dependency error

- pyang/plugins/threegpp.py
- test/plugins/test_threegpp/Makefile
- test/plugins/test_threegpp/_3gpp-correct.yang
- test/plugins/test_threegpp/_3gpp-incorrect.yang
- test/plugins/test_threegpp/_3gpp-missing-incorrect2.yang
- test/plugins/test_threegpp/ietf-yang-types@2013-07-15.yang
- test/plugins/test_threegpp/incorrect-3gpp.expect
- test/plugins/test_threegpp/missing-incorrect2-3gpp.expect
- test/plugins/test_threegpp/twogpp-wrongFileName.expect
- test/plugins/test_threegpp/twogpp-wrongFileName.yang
The provided plugin checks that a YANG module follows the 3gpp YANG style as documented in 3GPP TS 32.160.
It can be invoked with the --3gpp command line option
> Pyang plugin for checking 3GPP style for YANG modules

- pyang/plugins/sid.py
- test/test_sid/test-20-expected-ieee802-dot1q-psfp@2020-07-07.sid
- test/test_sid/test-5-expected-ietf-constrained-voucher@2019-08-01.sid
All data nodes part of a grouping and subsequent inner groupings needs to be associated with the module performing the initial "uses".
> Second fix for issue 716

- pyang/plugins/check_update.py
- test/test_update/Makefile
- test/test_update/expect/k.out
- test/test_update/k.yang
- test/test_update/k@2014-04-01.yang
If yang-version is not present in the module and the revision is bad
when updating, the following crash occurs since `stmt.i_module`
has no  `i_versions` attribute.
```
pyang --print-error-code --check-update-from k.yang k@2014-04-01.yang 
Traceback (most recent call last):
File "/home/avtobiff/src/github/avtobiff/pyang/bin/pyang", line 545, in <module>
run()
File "/home/avtobiff/src/github/avtobiff/pyang/bin/pyang", line 445, in run
p.post_validate_ctx(ctx, modules)
File "/home/avtobiff/src/github/avtobiff/pyang/pyang/plugins/check_update.py", line 165, in post_validate_ctx
check_update(ctx, modules[0])
File "/home/avtobiff/src/github/avtobiff/pyang/pyang/plugins/check_update.py", line 218, in check_update
chk_module(ctx, oldmod, newmod)
File …
```
> Avoid crash updating bad revision module without yang-version stmt

- pyang/statements.py
- pyang/translators/yang.py
- test/test_issues/test_i760/Makefile
- test/test_issues/test_i760/mod1.expect
- test/test_issues/test_i760/mod1.yang
Currently the "parent" property in Statement class is not purely used for statement tree.
But this property is used for line end comment printing. So we need one "stmt_parent" property more. This property will not be modified since Statement init.
This will fix #760 issue.
@mbj4668 Please review this.
> Bugfix #760: augment stmt expanding cause line end comment no printing

- test/test_bad/Makefile
If the tests are being run as the root user then the access.yang test
will fail, since it can always be read by the root user, even if the
read permission has been removed.
> test_bad: skip access.yang if running as root

- pyang/translators/yang.py
- test/test_yang/Makefile
- test/test_yang/expect/presence_bug_i775--yang-line-length_65.yang
- test/test_yang/expect/presence_bug_i775--yang-line-length_66.yang
- test/test_yang/expect/presence_bug_i775.yang
- test/test_yang/presence_bug_i775--yang-line-length_65.yang
- test/test_yang/presence_bug_i775--yang-line-length_66.yang
- test/test_yang/presence_bug_i775.yang
I added some comments to the commit. In summary, I think there were two problems:
- `line_len` was already incremented on the assumption that the argument is a single line (so it added 1 for the closing quote and 1 or 2 for `;` or ` {`)
- `need_new_line()` was called with `line_len + 1` that I think should be `line_len`
The first problem accounted for an error of `2` and the second for an error of `1`, giving the observed error of `3`.
> Fixes #775 - correct multi-line argument wrapping when generating YANG

- pyang/xpath_parser.py
When multiple Pyang instances are run in parallel, one instance may overwrite the parse table files at the same time they are read by another instance. Consequently, the second instance crashes when failing to interpret truncated Python code. By disabling writing tables to files, this race is avoided.
> Disable writing of Yacc parse tables to files

- bin/pyang
The option `--plugindir` does not understand the form `--plugindir=<dir>`; all other options do, so this might be quite confusing.
> plugindir option can have the form '--plugindir=<dir>'

- pyang/statements.py
Thanks to @jboyd77 for pointing out this problem, and for the fix.
See issue #802 for context. The proposed fix adds an `_init_i_attrs()` method (called from `ModSubmodStatement.__init__()` and `ModSubmodStatement.internal_reset()`) in order to prevent this from happening again the next time such an internal attribute (i.e., one that requires initialization) is added. It already happened in PR #580!
I didn't add a test case (the change seems rather obviously to fix the problem) but could do so if requested.
> Fixes #802 - init i_is_primary_module attribute

- pyang/syntax.py
- test/test_issues/test_i809/Makefile
- test/test_issues/test_i809/project@2022-04-07/project@2022-04-07.yang
If `bin/pyang` is given a path to a YANG file which contains more than
one '@' character (e.g. if there's an '@' in a parent directory), the
`re_filename` regexp will detect the revision-date as being everything
from the first instances of the '@' char in the path, to the yang/tin
suffix(es).
This fails to match the expected 'YYYY-MM-DD' date format that the
revision-date in the filename should take and `pyang` fails.
This commit fixes `re_filename` regexp so that it disregards all
characters in the filepath before the last directory separator (based
on the value of `os.sep`) in the string.
> Fix issue #809: revision-date parsed wrong if >1 @ in path

- test/test_feature/Makefile
- test/test_feature/include-exclude-different.expect
1. 
In `test/test_feature` directory,  the *.expect files are needed for diff, but `make clean` will delete them. So I remove the `make clean` in `Makefile`
2. Output are not symmetrical, I adjust a bit in `feature.py` and the expect files.
3. `include-exclude-different` failed, I modify the expect file.
Please have a look at this. Thanks @wlupton
> bugfix: test_feature make test failed and remove make clean

- pyang/plugins/sid.py
- test/test_sid/.gitignore
- test/test_sid/Makefile
- test/test_sid/test-1-expected-output.txt
- test/test_sid/test-2-expected-toaster@2009-11-20.sid
- test/test_sid/test-20-expected-ieee802-dot1q-psfp@2020-07-07.sid
- test/test_sid/test-21-expected-output.txt
- test/test_sid/test-21-expected-toaster@2009-12-28.sid
- test/test_sid/test-3-expected-output.txt
- test/test_sid/test-3-expected-toaster@2009-12-28.sid
- test/test_sid/test-5-expected-ietf-constrained-voucher@2019-08-01.sid
- test/test_sid/test-7-expected-toaster@2019-01-01.sid
1. added new item attribute "status", which may be "unstable" or a module_revision.
2. When --sid-finalize is set, then write all items that are "unstable" out with a provide module_revision.
More and more, perhaps "unstable" should be "provisional"
> Sid item status

- pyang/plugins/check_update.py
- test/test_update/expect/j.out
- test/test_update/j.yang
- test/test_update/j@2014-04-01.yang
check_update.py's chk_when() checks for newly added/changed 'when' constraints and should emit CHK_NEW_WHEN/CHK_UNDECIDED_WHEN errors.
After updating to YANG 1.1 we found that check_update does not report new/changed when constraints properly.
This PR includes a simple fix to chk_when() (changes elif to if) so that errors are properly reported. It also adds a test case for a new/changed when constraints in a 1.1 model.
**UT Results**
With UT changes but without chk_when() fix we see that the expected errors are not produced
```
trying a... ok
trying c... ok
trying f... ok
trying h... ok
trying i... ok
trying j...2,3d1
< j@2014-04-01.yang:14: error: CHK_NEW_WHEN
< j@2014-04-01.yang:18: warning: CHK_UNDECIDED_WHEN
make: *** [test] Error 1
```
With chk_when() fix:
```
> make
trying a... ok …
```
> check_update does not validate 'when' constraints for YANG 1.1 models

- pyang/plugins/uml.py
Avoid PlantUML syntax error by defining an empty package before defining the note with annotations on top of package (from 1.2023.2 PlantUML has stricter syntax requiring packages be defined before referencing them, e.g., in a note.
> Fix issue #861: Avoid PlantUML syntax error (from PlantUML release 1.2023.2)

- pyang/plugins/uml.py
In the class representing the module in the rendered UML, the name of features defined within the module and the deviated nodes are displayed as PlantUML keywords rather than the YANG identifier for a feature or the node within the schema tree for a deviation. This change corrects these issues.
Note that the handling of deviation statements may need further improvements.
> Correct display of features and deviations within the module class for UML plugin

- pyang/plugins/uml.py
If the 'module' in the option --uml-no, then the attribute thismod-prefix is not defined, but it is still needed regardless of whether the module is shown as package in the UML or not. 
This correction moves the definition of thismod-prefix out of the function emit_module_header() into the function emit() at the point where each module in the list of input modules is processed, immediately before the test for ctx_no_module and the call to emit_module_header().
This change can be tested by creating a UML from ietf-hardware with the option --uml-no=module.
Without this change pyang outputs the following:
```
Info: Leafref ../../component/name outside diagram. Prefix = 
Info: Leafref ../../component/name outside diagram. Prefix = 
Info: Leafref /hardware/component/name outside diagram. …
```
> Move definition of thismod-prefix from emit_module_header() to emit() for UML plugin

- pyang/plugins/uml.py
Each imported module of a module being rendered is to be shown an empty packages with a relation from the imported package to the package representing the module. 
PlantUML does not render this correctly. This is because the relations are defined within the package representing the module being processed, causing PlantUML keyword referencing the module (package) in the relation definition to be interpreted as a new class. 
This correction moves the definitions of the relations to outside of the package, so that the keyword referencing the module (package) is interpreted as the package representing the module being processed.
This change can be verified by creating a UML from ietf-hardware without any UML-specific option specified. 
Without this change pyang outputs the following:
With …
> Correct issue with the rendering of imported modules for UML plugin

- pyang/scripts/pyang_tool.py
It is sometimes annoying that pyang throws a FileExistsError if an output file already exists, such as when generating PlantUML code for a YANG module, for example, when the YANG module is updated. Currently, an existing PlantUML file has to be deleted before invoking pyang.
This pull requests adds a new option -O, --overwrite to allow the user to choose to overwrite the output file, if it already exists. By default the option is false and so this change is backwards compatible.
> Add a new option to overwrite an output file, if it already exists

- pyang/plugins/uml.py
Companies may have their own guidelines on how YANG models are rendered in UML, such as rendering the relationship from an interior node to a choice statement as composition rather than a dotted line. This pull requests adds new UML-specific options to control some aspects of the rendering of UML and extends the --uml-no option to suppress additional parts of the diagram as detailed below.
--uml-no:
Adds the following new values 
- "prefix" to suppress the use of the module prefix in the name of the package representing a module, including imported modules.
- "title", "footer" to suppress the diagram's title and footer to allow a title and/or footer to be generated in a separate include file, for example, according to a company's best practice guidelines.
--uml-max-bits:
Currently pyang …
> UML Plugin: Add new options to allow more control as to how the PlantUML code is rendered

- pyang/plugins/uml.py
When a module uses a grouping in an imported module that is not in the list of input files, the uses reference to that grouping cannot be rendered.
When this occurs the UML Plugin issues an info message indicating that the reference to a grouping has been skipped using the PlantUML keyword of the parent node of the uses statement rather than the more understandable actual name of the grouping. It would be expected that PlantUML keywords would be cryptic to most users who are not interested in the details of the PlantUML code. 
This pull request modifies this info message to quote the name of the grouping. The change can be verified using ietf-yang-patch@2017-02-22 as an example.
If module ietf-yang-patch@2017-02-22 is the only input file and the UML as the output format is selected, then …
> UML Plugin: Improve info message when a uses reference is skipped

- pyang/plugins/uml.py
PlantUML does not accept dots in keywords, but the current UML plugin does not convert dots in keywords (as permitted for YANG identifiers by RFC 7950 section 6.2) to underscores in the function make_plantuml_keyword(). 
This fix replaces dots with 2 underscores to ensure there is no chance of a clash of keywords where say both the identifiers 'a.b' and 'a-b' exist.
If PlantUML code is generated from the following test module (no specific UML-specific option specified), PlantUML brings an error.
```
module test-identifier-dots {
yang-version 1.1;
namespace "http://www.example.com/ns/yang/test-identifier-dots";
prefix tst-id-dots;
revision 2023-07-17 {
description
"Initial revision.";
reference
"None.";
}
identity base-identity {
description
"Base identity for identities.";
}
identity a { …
```
> UML Plugin: Fix dots in identifiers not being converted to underscore in PlantUML keywords

- pyang/plugins/uml.py
This pull request fixes issues with the rendering of identities, identities, typedefs and leafrefs and relations associated with them:
1. Fix missing stereotype \<\<enumeration\>\> on the enumeration class.
1. Fix the false identification of the source of an identityref when the source is a typedef.
1. Fix multiple identical base ids in self.baseid which result in duplicate definitions in the PlantUML code (note this has no effect on the diagram as such).
1. Fix multiple identical identities in self.identities which result in duplicate definitions in the PlantUML code (note this has no effect on the diagram as such).
1. Fix base identities from being rendered in modules in which they are not used.
- This was caused by a typo in attribute name in the function post_process_module(), so that …
> UML Plugin: Fix issues with the rendering of identities, identityrefs, typedefs, leafrefs

- pyang/plugins/uml.py
Notifications defined in interior data nodes (containers, lists) are not rendered in the UML diagram generated by the UML Plugin. 
This pull request fixes this shortcoming,
The following example illustrate what has been fixed.
The following YANG data model were used to test this fix:
<details>
<summary>test-notifications</summary>
```
module test-notifications {
yang-version 1.1;
namespace "http://www.example.com/ns/yang/test-notifications";
prefix tst-nfc;
revision 2023-07-21 {
description
"Initial revision.";
reference
"None.";
}
grouping notificatication-grouping {
description
"A grouping defining a notification.";
notification grp-nfc {
description
"A notification in a list.";
leaf binary-leaf {
type binary;
description
"A leaf in a notification that is in a list.";
}
}
}
container …
```
> UML Plugin: Fix missing notifications defined in interior data nodes

- pyang/plugins/check_update.py
If other modules import this code, an exit in a library may have unintended consequences.  Like in other places, use return instead of exit.
> Replace sys.exit with return.

- pyang/plugins/uml.py
When using the UML option --uml-uses=generalization or --uml-uses=realization added with PR #868, the generalization or realization relation is rendered the wrong way around. 
Assuming that a grouping is considered an abstract class (superclass), then the class which includes the uses statement can be considered the subclass of this abstract class (the grouping) and thus a generalization relation should define a path from the subclass to the superclass with the hollow triangle at the end of the path where it meets the more general superclass.
The following example illustrate what has been fixed.
<details>
<summary>The YANG data model used to test this fix</summary>
```
module test-uses-grouping {
namespace "http://www.example.com/ns/yang/my-uses-module-1";
prefix tst-uses-grp;
revision …
```
> UML Plugin: Fix direction of the generalization and realization versions of th uses relation

- pyang/plugin.py
Depending on Python version use pkg_resources (old behavior) or use importlib to check for plugins.
Closes #911
> Replace deprecated pkg_resources with importlib for Python >=3.12

- doc/pyang.1.md
It was not clear from earlier description that `deref()` restriction
was limited to YANG 1.0 modules/submodules.
It is now explicitly stated so.
This addresses #928
> man: Clarify `--strict` argument description

- bin/yang2dsdl
When pyang is user-installed (i.e. into .local/), PYANG_XSLT_DIR and PYANG_RNG_LIBDIR would have to be specified.
With this, they are looked up relative to the yang2dsl script.
When running from a git checkout, the paths are different once again, also detected by looking for .git/ and setup.py.
> detect xslt_dir and schema_dir in yang2dsdl

- pyang/plugins/uml.py
When rendering YANG modules with a 'uses' statement at the module level, such as can be found the YANG module openconfig-telemetry@2018-11-21, the top-level uses statement is ignored. This pull request fixes this issue.
The following examples illustrate what has been fixed.
The following YANG data models were used to test this fix:
<details>
<summary>test-groupings</summary>
```
module test-groupings {
namespace "http://www.adtran.com/ns/yang/test-groupings";
prefix tst-grp;
revision 2024-03-11 {
description
"Initial revision.";
reference
"None.";
}
grouping grouping-1 {
description
"A grouping with a top-level non-interior data node.";
leaf a-top-level-leaf-in-a-grouping {
type string;
description
"Bla bla bla.";
}
}
grouping grouping-2 {
description
"A grouping with a top-level interior …
```
> UML Plugin: Fix top-level uses statement being ignored
