- setup.py
If the installation is on windows, place pyang.bat file in Scripts directory
> pyang batch script

- pyang/plugins/sample-xml-skeleton.py
Added new option to sample-xml-skeleton output format.
--sample-xml-skeleton-path (subtree to print)
> Add option --sample-xml-skeleton-path (Subtree to print)

- pyang/translators/dsdl.py
> Fix grouping deviation issue

- pyang/plugins/depend.py
- pyang/plugins/uml.py
Please let me know if you'd like an example that demonstrates the problem.
> Don't assume that errors have 'top' attributes

- setup.py
This fix address https://github.com/mbj4668/pyang/issues/310
> create bat file win env also

- pyang/statements.py
> Recognize mandatory choice/anyxml/anydata nodes. Fixes #383.

- doc/pyang.1.dbk
Document the --name-print-revision option to the name plugin.
> Update docbook text.

- pyang/statements.py
Signed-off-by: miroslav.kovac <miroslav.kovac@pantheon.tech>
> Fix bugs with union and empty literal

- pyang/plugins/check_update.py
Minor fix for YANG 1.0 and also a bit modification for YANG 1.1.
> Fix issue#431 in chk_identity()

- pyang/translators/dsdl.py
A proposed fix for issue https://github.com/mbj4668/pyang/issues/260
> correct schema path generation from unique statements

- pyang/statements.py
- test/test_issues/test_i430/Makefile
- test/test_issues/test_i430/a.yang
- test/test_issues/test_i430/xpath.yang
Signed-off-by: miroslav.kovac <miroslav.kovac@pantheon.tech>
> Fix issue 430

- pyang/statements.py
These can help a lot when debugging (I'll add a screenshot to the PR).
> Add simple Statement.__str__() and __repr__() methods

- pyang/statements.py
- test/test_issues/test_i545/Makefile
- test/test_issues/test_i545/mod1.expect
- test/test_issues/test_i545/mod1.yang
- test/test_issues/test_i545/mod2.yang
> fix #545 if-feature statements should do the status check for each feature

- bin/pyang
- pyang/plugins/sid.py
- pyang/plugins/tree.py
- pyang/statements.py
- pyang/syntax.py
- pyang/types.py
- pyang/util.py
- test/test_issues/test_o001/Makefile
- test/test_issues/test_o001/expect/m.out
- test/test_issues/test_o001/m.yang
- test/test_issues/test_o001/plugins/composed.py
- test/test_issues/test_o001/s.yang
A batch of small improvements and possibly obscure bugfixes.
> Pylint batch2

- pyang/transforms/__init__.py
- setup.py
I noticed that the `edit` transform wasn't available in pyang 2.2.
> Add transforms to the distribution

- doc/pyang.1.dbk
- man/man1/pyang.1
- pyang/transforms/edit.py
Also some minor changes to the transform itself (only to comments, not code).
> Add documentation of the 'edit' transform

- pyang/error.py
- pyang/statements.py
- test/test_issues/test_i583/Makefile
- test/test_issues/test_i583/expect/mod1.expect
- test/test_issues/test_i583/expect/mod2.expect
- test/test_issues/test_i583/mod1.yang
- test/test_issues/test_i583/mod2.yang
> Bugfix the default value in leaf node should not be marked with an if-feature statements

- pyang/statements.py
> Refactor: remove a redundant function

- pyang/statements.py
- test/test_issues/test_i599/Makefile
- test/test_issues/test_i599/expect/mod1.expect
- test/test_issues/test_i599/mod1.yang
> Bugfix #599: fix crash when input defined in anydata node

- pyang/error.py
- pyang/statements.py
- test/test_issues/test_i597/Makefile
- test/test_issues/test_i597/expect/mod1.expect
- test/test_issues/test_i597/mod1.yang
> Bugfix #597: the target node of augment stmt cannot be action node

- pyang/types.py
- test/test_issues/test_i322/mod1.yang
Hi Martin @mbj4668 , If you have time, please have a look at this PR.
But I am not sure whether we should reserve the XSDPattern class. Currently I do the least modification to fix this issue.
> Bugfix #587:regular expression validation replace xsd schema with re library 

- pyang/types.py
- test/test_issues/test_i322/mod1.yang
> Revert "Bugfix #587:regular expression validation replace xsd schema with re library "

- pyang/plugins/flatten.py
> Add choice "excel-semicolon" to option --flatten-csv-dialect

- etc/bash_completion.d/pyang
have is deprecated and not available in certain systems,
use _have, the recommended function instead
> fix bash completion script

- pyang/statements.py
- test/test_tree/Makefile
- test/test_tree/aug.tree.expect
- test/test_tree/feature-pruned.tree.expect
- test/test_tree/feature.tree.expect
- test/test_tree/feature.yang
Please see #780 for background.
> Prune augmented nodes that are disabled due to disabled feature

- pyang/plugins/depend.py
- test/plugins/test_depend/Makefile
- test/plugins/test_depend/a-sub@2022-03-29.yang
- test/plugins/test_depend/a@2022-03-29.yang
- test/plugins/test_depend/b@2022-02-20.yang
- test/plugins/test_depend/c@2022-01-01.yang
- test/plugins/test_depend/c@2022-02-02.yang
- test/plugins/test_depend/d@2022-03-03.yang
This resolves #792 
Signed-off-by: Slavomir Mazur <slavomir.mazur@pantheon.tech>
> Consider the revision-date for emit_depend() method

- pyang/plugins/tree.py
Fix "'bool' object does not support item deletion"
> Fix#516: Crash in tree print

- pyang/plugins/ieee.py
- test/plugins/test_ieee/Makefile
- test/plugins/test_ieee/ieee-802-dot1q-incorrect-name.expect
- test/plugins/test_ieee/ieee-802-dot1q-incorrect-name.yang
- test/plugins/test_ieee/ieee802-dot1q-correct.yang
- test/plugins/test_ieee/ieee802-dot1q-incorrect-namespace.expect
- test/plugins/test_ieee/ieee802-dot1q-incorrect-namespace.yang
This addresses mbj4668/pyang#893
> Fix IEEE module name prefix expectation

- pyang/types.py
I need to access the fraction-digits in my plugin. It would be great if we could add it to the Decimal64Value object.
Thanks
> Add fd to Decimal64Value

- pyang/statements.py
> Append config statement when replacing true -> false
